kind: Service
apiVersion: v1
metadata:
  name: bamoe-canvas-ui
  namespace: bamoe-v921
  uid: 569fafd2-c857-44bb-9521-26d95478d1d7
  resourceVersion: '68506'
  creationTimestamp: '2025-08-07T02:26:02Z'
  labels:
    app: bamoe-canvas-ui
    app.kubernetes.io/component: bamoe-canvas-ui
    app.kubernetes.io/instance: bamoe-canvas-ui
    app.kubernetes.io/part-of: bamoe-v921
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2025-08-07T02:26:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
    - manager: kubectl-label
      operation: Update
      apiVersion: v1
      time: '2025-08-07T02:26:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:app.kubernetes.io/part-of': {}
spec:
  clusterIP: 10.217.4.204
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.217.4.204
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: bamoe-canvas-ui
status:
  loadBalancer: {}
