kind: Service
apiVersion: v1
metadata:
  name: bamoe-management-console
  namespace: bamoe-v930
  uid: a7c779eb-a8cc-42e3-a10e-209af06bdaa9
  resourceVersion: '9383309'
  creationTimestamp: '2025-10-12T17:23:20Z'
  labels:
    app: bamoe-management-console
    app.kubernetes.io/component: bamoe-management-console
    app.kubernetes.io/instance: bamoe-management-console
    app.kubernetes.io/part-of: bamoe-v930
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2025-10-12T17:23:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
    - manager: kubectl-label
      operation: Update
      apiVersion: v1
      time: '2025-10-12T17:23:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:app.kubernetes.io/part-of': {}
spec:
  clusterIP: 10.217.5.64
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.217.5.64
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: bamoe-management-console
status:
  loadBalancer: {}
