kind: Service
apiVersion: v1
metadata:
  name: bamoe-canvas-ui
  namespace: bamoe-v931
  uid: 074592dd-f678-44e4-90e3-f383b5bc4e78
  resourceVersion: '9380123'
  creationTimestamp: '2025-10-12T17:00:39Z'
  labels:
    app: bamoe-canvas-ui
    app.kubernetes.io/component: bamoe-canvas-ui
    app.kubernetes.io/instance: bamoe-canvas-ui
    app.kubernetes.io/part-of: bamoe-v931
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2025-10-12T17:00:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
    - manager: kubectl-label
      operation: Update
      apiVersion: v1
      time: '2025-10-12T17:00:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:app.kubernetes.io/part-of': {}
spec:
  clusterIP: 10.217.4.152
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.217.4.152
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: bamoe-canvas-ui
status:
  loadBalancer: {}
